[package]
name = "koe-call"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serenity.workspace = true
songbird.workspace = true
symphonia.workspace = true

[lints]
workspace = true
