[package]
name = "koe-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
tokio = { version = "1.37.0", features = ["fs"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.27"
