services:
  app:
    image: ghcr.io/ciffelia/koe:1.0.0
    init: true
    depends_on:
      - redis
      - voicevox
    restart: unless-stopped
    environment:
      RUST_LOG: warn
    volumes:
      - "./config/koe.yaml:/etc/koe.yaml:ro"

  redis:
    image: redis:7.0.5
    command: /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "redis-data:/data"

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.13.1
    restart: unless-stopped
    expose:
      - 50021
    volumes:
      - "./config/voicevox_presets.yaml:/opt/voicevox_engine/presets.yaml:ro"

volumes:
  redis-data:
